project_id = "ifpqsyyvytfpossqycpc"

[functions.parse-recipe-image]
verify_jwt = false

[functions.analyze-recipe]
verify_jwt = false

[functions.home-assistant]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.webhook-recipe]
verify_jwt = false

[functions.generate-recipe-image]
verify_jwt = false

[functions.validate-ai-key]
verify_jwt = false

[functions.manage-cookidoo-credentials]
verify_jwt = false

[functions.export-recipe-cookidoo]
verify_jwt = false
